### ISSUE TITLE
Cannot find module 'jasmine-es6-promise-matchers' thrown when trying to require(...)

### ISSUE THREAD

**Issue by guncha** [bvaughn/jasmine-es6-promise-matchers#4]
The error is thrown when trying to require the library that's installed via NPM. Seems like it's happening because of an invalid "main" entry in the library's `package.json` file. If that's updated to `jasmine-es6-promise-matchers.js`, the require fails due to `window` not being a thing in the Node world.

**Comment by bvaughn** [comment]
Hi @guncha,

My apologies for taking so long to reply to this issue. I have been very busy with a new job and have had trouble keeping up with all of my open source Github projects.

I've just committed an update that I think *might* resolve your issue but please let me know if it doesn't. I'd be happy to accept a pull request from you too, if you'd like to add anything. :)

**Comment by bvaughn** [comment]
Going to close as inactive. :)
