### ISSUE TITLE
undefined when resolved with empty object

### ISSUE THREAD

**Issue by CThuleHansen** [bvaughn/jasmine-es6-promise-matchers#5]
I am trying to verify a promise has been resolved with an empty object, but I get the error:
undefined at node_modules/jasmine-es6-promise-matchers/jasmine-es6-promise-matchers.js:47:13

Test: expect(x.y()).toBeResolvedWith({});

**Comment by CThuleHansen** [comment]
I had $rootscope.apply after the expect, and that made it fail.

**Comment by bvaughn** [comment]
Glad to hear you got it resolved :)
